Repository opnDMS/opnDMS, pull requests merged in 2023-04, with the labels that each got.

#1 Add resources
  index.html
  res/css/fonts.css
  res/css/main.css
  res/fontawesome/css/all.css
  res/fontawesome/css/all.min.css
  res/fontawesome/css/brands.css
  res/fontawesome/css/brands.min.css
  res/fontawesome/css/fontawesome.css
  res/fontawesome/css/fontawesome.min.css
  res/fontawesome/css/regular.css
  res/fontawesome/css/regular.min.css
  res/fontawesome/css/solid.css
  res/fontawesome/css/solid.min.css
  res/fontawesome/css/svg-with-js.css
  res/fontawesome/css/svg-with-js.min.css
  res/fontawesome/css/v4-font-face.css
  res/fontawesome/css/v4-font-face.min.css
  res/fontawesome/css/v4-shims.css
  res/fontawesome/css/v4-shims.min.css
  res/fontawesome/css/v5-font-face.css
  res/fontawesome/css/v5-font-face.min.css
  res/fontawesome/webfonts/fa-brands-400.ttf
  res/fontawesome/webfonts/fa-brands-400.woff2
  res/fontawesome/webfonts/fa-regular-400.ttf
  res/fontawesome/webfonts/fa-regular-400.woff2
  res/fontawesome/webfonts/fa-solid-900.ttf
  res/fontawesome/webfonts/fa-solid-900.woff2
  res/fontawesome/webfonts/fa-v4compatibility.ttf
  res/fontawesome/webfonts/fa-v4compatibility.woff2
  res/fonts/inter-v12-latin-900.eot
  res/fonts/inter-v12-latin-900.svg
  res/fonts/inter-v12-latin-900.ttf
  res/fonts/inter-v12-latin-900.woff
  res/fonts/inter-v12-latin-900.woff2
  res/fonts/inter-v12-latin-regular.eot
  res/fonts/inter-v12-latin-regular.svg
  res/fonts/inter-v12-latin-regular.ttf
  res/fonts/inter-v12-latin-regular.woff
  res/fonts/inter-v12-latin-regular.woff2
  res/js/jquery/jquery-3.6.1.min.js
  res/js/jquery/jquery-3.6.1.min.map
Labels: enhancement

#7 Fix logical error
  login/logincheck.php
Labels: bug, backend, URGENT

#8 Add codeql
  .github/workflows/codeql.yml
Labels: enhancement

#12 Frontend
  index.php
  login/index.html
  login/style.css
  res/css/index.css
  res/css/main.css
Labels: frontend

#11 Add file upload - backend
  upload/index.php
  upload/upload-file.php
Labels: enhancement, backend

#14 I10 themesjs missing
  .github/workflows/codeql.yml
  index.php
  login/index.html
Labels: Clean up

#15 get new content
  .github/workflows/codeql.yml
  index.php
  login/index.html
  upload/index.php
  upload/upload-file.php
Labels: frontend

#21 create first Styling for upload page
  index.php
  res/css/main.css
  upload/index.php
  upload/style.css
  upload/style.js
Labels: frontend, Clean up
